highlighter: rouge
markdown: kramdown
gist:
  noscript: false
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude: [mediawiki]
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
title: GMOD
logo: images/GMOD-cogs.png
favicon: favicon.ico
